// <auto-generated />
namespace ExchangeRates.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddExchangeRateClass : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206150549338_AddExchangeRateClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so9N303m2vMhfZW3ejOnNNn/XfpQel0VGyLzOy/P3xGznITD7yPZJvZ4Sdu31m+tVzj2Hnfotqe3vlV8HH9BHL+tqldft9av8XN9/ivfSuzc3PFnXNdH/utv48d1uP/bloAvgLL+/Ifp+lL5Yl2U2Kemz86xsejh0gbjuBdDrtiZG+Ch9VrzLZ8/z5UU7t5C+yN6ZT3b3Dj5Kv1oWxDf0Uluv37/nVz76+bRYZOVH6cuaflPOpB5eTzPA+/QG4I/vuvnrzyo4JiuWeR2ZWsNNIaby3uu8jbzRfJS6zoT9xgGzRDGzODhGvyucbiTi7oBIPP4iW61oSjwR0U/S1yIfJ9uv318AFgLj7rSJyIHF1vbUVnV2kXe+pa4J02dF3bTEf9kkw7yczBa9Zu9BcdNjjPBdYXLzYN7C75E3jdIIJ6oDzhH2GY11kS9bHrYOmlDbpBQUAPg1q6NyelKV68Vyk3IYhuCE1IcypDk2QXrVw6XPs/r+3Q41utT3ZE5bdvRXd043iUW3ie3dikdHDB4rS95sPno8Kk2ga6rLYgb+fH3dtPlijAbj17+oPCkLGq9r8EW2LM7zpn1Tvc1hCkmEvr75eXh3Zw/m527TzMr/X9mgGf0OG//elqBrg5aXWU0jr/sW5z0B+yZm9sM0MX29eHsDc6N9Ef6lEU0qGpxg3LFQX9ME9WXq8V3fcXv8NG+KCwcCbtwyn7ZETAfUtDlbnldmPmikPkamSWe6vsjbjJgoO67b4jybtvT1NG8a9kd+MivXGOdiks/Oll+u29W6PW6afDEpA7Z9fHdz/2xnQ5wff7nCX54S+fpDIDQLyMGXyyfropxZvJ9FOGoABHjn85w+z4AV+WME7uLaQnpRLW8JSMn3NF/lyxkptDf5YlWCP75cvs4u82HcbqZhSLHHT4vsos4WPgXlE8XkdUY9e11QB/4brj/6k9iVooaj/ycAAP//PZQXEqoMAAA="; }
        }
    }
}
