// <auto-generated />
namespace ExchangeRates.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddRequestMessageClass : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206150556525_AddRequestMessageClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so9N303m2vMhfZW3ejOnNNn/XfpQel0VGyLzOy/P3xGznITD7yPZJvZ4Sdu31m+tVzj2Hnfotqe3vlV8HH9BHL+tqldft9av8XN9/ivfSuzc3PFnXNdH/utv48d1uP/bloAvgLL+/Ifp+lL5Yl2U2Kemz86xsejh0gbjuBdDrtiZG+Ch9VrzLZ8/z5UU7t5C+yN6ZT3b3Dj5Kv1oWxDf0Uluv37/nVz76+bRYZOVH6cuaflPOpB5eTzPA+/QG4I/vuvnbOKuv8l+0zpv2i7xpsouvNa/66tnT958v71UZ9dmyvbcXGdrq00ev26rOP8+XeU1Umr3M2javiSZns5yHpAz/aPXp7Xj+4d2dPfD83Wy5rNqsJQLfND1vqrf58j25gn7dwBXy9+ZewcfPi6b9We54M8NAxWQF0T6iC4z6CUch773O28gbzUep60z01TjQLl2SdIGFTBsD12Hr6FDtoJyqvSu61ujkuwNK+fEX2WpFs+Apaf0kfS0a+mT79fur4IXAuDttIprYYmt7IoGgsXW+pa4J02dF3bTEOdkkA1+czBa9Zu8xhabH2Ex29YObCfMWfo+8acxWOPMdcI6wz2isCxJ1HrYOmlDbZJYUADRmVkctxUlVrhfLTeZpGIIzEz6UIdu1CdKrHi4xIeD373ao0aW+J8TasqORu3N6qxnvituHz/kmq8Mgb5r1mwAM0dqzOD7BB23YJlhqD3w4+tHtYTjt3uVF+fSHzAM91dhtYnu3KrKjCh+rWrrZie3pKWkCj6e6LGbQUa+vmzZfjNFg/PoXlSdlQeN1Db7IlsU5cQFTnRxyUqNf3wm2DkHTzMr/X3nCM/odkcZ7+6NdT3h5mdU08rrv974nYN/Rnf28dHQL8PGNLu17kjVwUM1kbS2yd3c+1Ol8D2Dv50j2nZUBixQTvZu8SFEoxGKTigYiCHf80PdyNG/hZ8a67HmrX9MZ7WvWx3f9JMLjp3lTXDgQSCks8ylCGwfUtDlbnldm0mm8PkamSY+H24xUSXZct8V5Nm3p6ykNqUAw8pNZuQZxF5N8drb8ct2u1u1x0+SLSRkor8d3N/fPHneI8+MvV/jLMyVffwiEZgFt+OXyybooZxbvZxG9MgACDKsiS1hRMEbgLq4tpBfV8paAlHxP81W+hMC/yRerEkz55fJ1dpkP43YzDUOKPX5aZBd1tvApKJ8oJq8z6tnrgjrw33D90Z/ErpTBOvp/AgAA//+xRrM0NhMAAA=="; }
        }
    }
}
